# coding: utf-8

"""
    Gitee OpenApi

    All api provided by Gitee  # noqa: E501

    OpenAPI spec version: 1.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pygitee
from pygitee.models.comment import Comment  # noqa: E501
from pygitee.rest import ApiException


class TestComment(unittest.TestCase):
    """Comment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComment(self):
        """Test Comment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pygitee.models.comment.Comment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
