# coding: utf-8

"""
    getV5ReposOwnerRepoSubscribers

    列出 watch 了仓库的用户  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pygitee
from pygitee.models.number_testers_body1 import NumberTestersBody1  # noqa: E501
from pygitee.rest import ApiException


class TestNumberTestersBody1(unittest.TestCase):
    """NumberTestersBody1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNumberTestersBody1(self):
        """Test NumberTestersBody1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pygitee.models.number_testers_body1.NumberTestersBody1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
