# coding: utf-8

"""
    Gitee OpenApi

    All api provided by Gitee  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pygitee
from pygitee.models.api_reviewers import ApiReviewers  # noqa: E501
from pygitee.rest import ApiException


class TestApiReviewers(unittest.TestCase):
    """ApiReviewers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiReviewers(self):
        """Test ApiReviewers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pygitee.models.api_reviewers.ApiReviewers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
