# coding: utf-8

"""
    getV5ReposOwnerRepoSubscribers

    列出 watch 了仓库的用户  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pygitee
from pygitee.models.list import List  # noqa: E501
from pygitee.rest import ApiException


class TestList(unittest.TestCase):
    """List unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testList(self):
        """Test List"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pygitee.models.list.List()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
