# coding: utf-8

"""
    Gitee OpenApi

    All api provided by Gitee  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pygitee
from pygitee.models.setting_new_body import SettingNewBody  # noqa: E501
from pygitee.rest import ApiException


class TestSettingNewBody(unittest.TestCase):
    """SettingNewBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSettingNewBody(self):
        """Test SettingNewBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pygitee.models.setting_new_body.SettingNewBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
