# coding: utf-8

"""
    Gitee OpenApi

    All api provided by Gitee  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pygitee
from pygitee.models.in_reply_to_user import InReplyToUser  # noqa: E501
from pygitee.rest import ApiException


class TestInReplyToUser(unittest.TestCase):
    """InReplyToUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInReplyToUser(self):
        """Test InReplyToUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pygitee.models.in_reply_to_user.InReplyToUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
