# coding: utf-8

"""
    Gitee OpenApi

    All api provided by Gitee  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pygitee
from pygitee.models.number_testers_body import NumberTestersBody  # noqa: E501
from pygitee.rest import ApiException


class TestNumberTestersBody(unittest.TestCase):
    """NumberTestersBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNumberTestersBody(self):
        """Test NumberTestersBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pygitee.models.number_testers_body.NumberTestersBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
