# coding: utf-8

"""
    Gitee OpenApi

    All api provided by Gitee  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pygitee
from pygitee.api.comment_api import CommentApi  # noqa: E501
from pygitee.rest import ApiException


class TestCommentApi(unittest.TestCase):
    """CommentApi unit test stubs"""

    def setUp(self):
        self.api = CommentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_enterprises_enterprise_issues_number_comments_get(self):
        """Test case for enterprises_enterprise_issues_number_comments_get

        获取企业某个Issue所有评论  # noqa: E501
        """
        pass

    def test_enterprises_enterprise_week_reports_id_comment_post(self):
        """Test case for enterprises_enterprise_week_reports_id_comment_post

        评论周报  # noqa: E501
        """
        pass

    def test_enterprises_enterprise_week_reports_id_comments_get(self):
        """Test case for enterprises_enterprise_week_reports_id_comments_get

        某个周报评论列表  # noqa: E501
        """
        pass

    def test_enterprises_enterprise_week_reports_report_id_comments_id_delete(self):
        """Test case for enterprises_enterprise_week_reports_report_id_comments_id_delete

        删除周报某个评论  # noqa: E501
        """
        pass

    def test_gists_gist_id_comments_get(self):
        """Test case for gists_gist_id_comments_get

        获取代码片段的评论  # noqa: E501
        """
        pass

    def test_gists_gist_id_comments_id_get(self):
        """Test case for gists_gist_id_comments_id_get

        获取单条代码片段的评论  # noqa: E501
        """
        pass

    def test_repos_owner_repo_comments_get(self):
        """Test case for repos_owner_repo_comments_get

        获取仓库的Commit评论  # noqa: E501
        """
        pass

    def test_repos_owner_repo_comments_id_get(self):
        """Test case for repos_owner_repo_comments_id_get

        获取仓库的某条Commit评论  # noqa: E501
        """
        pass

    def test_repos_owner_repo_commits_ref_comments_get(self):
        """Test case for repos_owner_repo_commits_ref_comments_get

        获取单个Commit的评论  # noqa: E501
        """
        pass

    def test_repos_owner_repo_commits_sha_comments_post(self):
        """Test case for repos_owner_repo_commits_sha_comments_post

        创建Commit评论  # noqa: E501
        """
        pass

    def test_repos_owner_repo_issues_comments_get(self):
        """Test case for repos_owner_repo_issues_comments_get

        获取仓库所有Issue的评论  # noqa: E501
        """
        pass

    def test_repos_owner_repo_issues_comments_id_get(self):
        """Test case for repos_owner_repo_issues_comments_id_get

        获取仓库Issue某条评论  # noqa: E501
        """
        pass

    def test_repos_owner_repo_issues_number_comments_get(self):
        """Test case for repos_owner_repo_issues_number_comments_get

        获取仓库某个Issue所有的评论  # noqa: E501
        """
        pass

    def test_repos_owner_repo_pulls_comments_id_get(self):
        """Test case for repos_owner_repo_pulls_comments_id_get

        获取Pull Request的某个评论  # noqa: E501
        """
        pass

    def test_repos_owner_repo_pulls_number_comments_get(self):
        """Test case for repos_owner_repo_pulls_number_comments_get

        获取某个Pull Request的所有评论  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
