# coding: utf-8

"""
    Gitee OpenApi

    All api provided by Gitee  # noqa: E501

    OpenAPI spec version: 1.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IssueTypeDetail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'color': 'str',
        'created_at': 'object',
        'id': 'int',
        'ident': 'str',
        'is_system': 'bool',
        'template': 'str',
        'title': 'str',
        'updated_at': 'object'
    }

    attribute_map = {
        'color': 'color',
        'created_at': 'created_at',
        'id': 'id',
        'ident': 'ident',
        'is_system': 'is_system',
        'template': 'template',
        'title': 'title',
        'updated_at': 'updated_at'
    }

    def __init__(self, color=None, created_at=None, id=None, ident=None, is_system=None, template=None, title=None, updated_at=None):  # noqa: E501
        """IssueTypeDetail - a model defined in Swagger"""  # noqa: E501
        self._color = None
        self._created_at = None
        self._id = None
        self._ident = None
        self._is_system = None
        self._template = None
        self._title = None
        self._updated_at = None
        self.discriminator = None
        if color is not None:
            self.color = color
        if created_at is not None:
            self.created_at = created_at
        if id is not None:
            self.id = id
        if ident is not None:
            self.ident = ident
        if is_system is not None:
            self.is_system = is_system
        if template is not None:
            self.template = template
        if title is not None:
            self.title = title
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def color(self):
        """Gets the color of this IssueTypeDetail.  # noqa: E501


        :return: The color of this IssueTypeDetail.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this IssueTypeDetail.


        :param color: The color of this IssueTypeDetail.  # noqa: E501
        :type: str
        """

        self._color = color

    @property
    def created_at(self):
        """Gets the created_at of this IssueTypeDetail.  # noqa: E501


        :return: The created_at of this IssueTypeDetail.  # noqa: E501
        :rtype: object
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this IssueTypeDetail.


        :param created_at: The created_at of this IssueTypeDetail.  # noqa: E501
        :type: object
        """

        self._created_at = created_at

    @property
    def id(self):
        """Gets the id of this IssueTypeDetail.  # noqa: E501


        :return: The id of this IssueTypeDetail.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this IssueTypeDetail.


        :param id: The id of this IssueTypeDetail.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def ident(self):
        """Gets the ident of this IssueTypeDetail.  # noqa: E501


        :return: The ident of this IssueTypeDetail.  # noqa: E501
        :rtype: str
        """
        return self._ident

    @ident.setter
    def ident(self, ident):
        """Sets the ident of this IssueTypeDetail.


        :param ident: The ident of this IssueTypeDetail.  # noqa: E501
        :type: str
        """

        self._ident = ident

    @property
    def is_system(self):
        """Gets the is_system of this IssueTypeDetail.  # noqa: E501


        :return: The is_system of this IssueTypeDetail.  # noqa: E501
        :rtype: bool
        """
        return self._is_system

    @is_system.setter
    def is_system(self, is_system):
        """Sets the is_system of this IssueTypeDetail.


        :param is_system: The is_system of this IssueTypeDetail.  # noqa: E501
        :type: bool
        """

        self._is_system = is_system

    @property
    def template(self):
        """Gets the template of this IssueTypeDetail.  # noqa: E501


        :return: The template of this IssueTypeDetail.  # noqa: E501
        :rtype: str
        """
        return self._template

    @template.setter
    def template(self, template):
        """Sets the template of this IssueTypeDetail.


        :param template: The template of this IssueTypeDetail.  # noqa: E501
        :type: str
        """

        self._template = template

    @property
    def title(self):
        """Gets the title of this IssueTypeDetail.  # noqa: E501


        :return: The title of this IssueTypeDetail.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this IssueTypeDetail.


        :param title: The title of this IssueTypeDetail.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def updated_at(self):
        """Gets the updated_at of this IssueTypeDetail.  # noqa: E501


        :return: The updated_at of this IssueTypeDetail.  # noqa: E501
        :rtype: object
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this IssueTypeDetail.


        :param updated_at: The updated_at of this IssueTypeDetail.  # noqa: E501
        :type: object
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IssueTypeDetail, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IssueTypeDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
