# coding: utf-8

"""
    Gitee OpenApi

    All api provided by Gitee  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Summary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'download_zip': 'int',
        'ip': 'int',
        'pull': 'int',
        'push': 'int'
    }

    attribute_map = {
        'download_zip': 'download_zip',
        'ip': 'ip',
        'pull': 'pull',
        'push': 'push'
    }

    def __init__(self, download_zip=None, ip=None, pull=None, push=None):  # noqa: E501
        """Summary - a model defined in Swagger"""  # noqa: E501
        self._download_zip = None
        self._ip = None
        self._pull = None
        self._push = None
        self.discriminator = None
        if download_zip is not None:
            self.download_zip = download_zip
        if ip is not None:
            self.ip = ip
        if pull is not None:
            self.pull = pull
        if push is not None:
            self.push = push

    @property
    def download_zip(self):
        """Gets the download_zip of this Summary.  # noqa: E501


        :return: The download_zip of this Summary.  # noqa: E501
        :rtype: int
        """
        return self._download_zip

    @download_zip.setter
    def download_zip(self, download_zip):
        """Sets the download_zip of this Summary.


        :param download_zip: The download_zip of this Summary.  # noqa: E501
        :type: int
        """

        self._download_zip = download_zip

    @property
    def ip(self):
        """Gets the ip of this Summary.  # noqa: E501


        :return: The ip of this Summary.  # noqa: E501
        :rtype: int
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this Summary.


        :param ip: The ip of this Summary.  # noqa: E501
        :type: int
        """

        self._ip = ip

    @property
    def pull(self):
        """Gets the pull of this Summary.  # noqa: E501


        :return: The pull of this Summary.  # noqa: E501
        :rtype: int
        """
        return self._pull

    @pull.setter
    def pull(self, pull):
        """Sets the pull of this Summary.


        :param pull: The pull of this Summary.  # noqa: E501
        :type: int
        """

        self._pull = pull

    @property
    def push(self):
        """Gets the push of this Summary.  # noqa: E501


        :return: The push of this Summary.  # noqa: E501
        :rtype: int
        """
        return self._push

    @push.setter
    def push(self, push):
        """Sets the push of this Summary.


        :param push: The push of this Summary.  # noqa: E501
        :type: int
        """

        self._push = push

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Summary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Summary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
