# coding: utf-8

"""
    Gitee OpenApi

    All api provided by Gitee  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'access_token': 'str',
        'bio': 'str',
        'blog': 'str',
        'name': 'str',
        'weibo': 'str'
    }

    attribute_map = {
        'access_token': 'access_token',
        'bio': 'bio',
        'blog': 'blog',
        'name': 'name',
        'weibo': 'weibo'
    }

    def __init__(self, access_token=None, bio=None, blog=None, name=None, weibo=None):  # noqa: E501
        """UserBody - a model defined in Swagger"""  # noqa: E501
        self._access_token = None
        self._bio = None
        self._blog = None
        self._name = None
        self._weibo = None
        self.discriminator = None
        if access_token is not None:
            self.access_token = access_token
        if bio is not None:
            self.bio = bio
        if blog is not None:
            self.blog = blog
        if name is not None:
            self.name = name
        if weibo is not None:
            self.weibo = weibo

    @property
    def access_token(self):
        """Gets the access_token of this UserBody.  # noqa: E501

        用户授权码  # noqa: E501

        :return: The access_token of this UserBody.  # noqa: E501
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token):
        """Sets the access_token of this UserBody.

        用户授权码  # noqa: E501

        :param access_token: The access_token of this UserBody.  # noqa: E501
        :type: str
        """

        self._access_token = access_token

    @property
    def bio(self):
        """Gets the bio of this UserBody.  # noqa: E501

        自我介绍  # noqa: E501

        :return: The bio of this UserBody.  # noqa: E501
        :rtype: str
        """
        return self._bio

    @bio.setter
    def bio(self, bio):
        """Sets the bio of this UserBody.

        自我介绍  # noqa: E501

        :param bio: The bio of this UserBody.  # noqa: E501
        :type: str
        """

        self._bio = bio

    @property
    def blog(self):
        """Gets the blog of this UserBody.  # noqa: E501

        微博链接  # noqa: E501

        :return: The blog of this UserBody.  # noqa: E501
        :rtype: str
        """
        return self._blog

    @blog.setter
    def blog(self, blog):
        """Sets the blog of this UserBody.

        微博链接  # noqa: E501

        :param blog: The blog of this UserBody.  # noqa: E501
        :type: str
        """

        self._blog = blog

    @property
    def name(self):
        """Gets the name of this UserBody.  # noqa: E501

        昵称  # noqa: E501

        :return: The name of this UserBody.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UserBody.

        昵称  # noqa: E501

        :param name: The name of this UserBody.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def weibo(self):
        """Gets the weibo of this UserBody.  # noqa: E501

        博客站点  # noqa: E501

        :return: The weibo of this UserBody.  # noqa: E501
        :rtype: str
        """
        return self._weibo

    @weibo.setter
    def weibo(self, weibo):
        """Sets the weibo of this UserBody.

        博客站点  # noqa: E501

        :param weibo: The weibo of this UserBody.  # noqa: E501
        :type: str
        """

        self._weibo = weibo

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
